### ISSUE TITLE
Sourcemaps test setup using Webpack plugin

### ISSUE THREAD

**Issue by thijsc** [appsignal/test-setups#12]
Create a test setup that has some Typescript frontend code. Have it post the generated source map with the webpack plugin.

**Comment by tombruijn** [comment]
Useful for https://github.com/appsignal/appsignal-javascript/issues/469#issuecomment-763573272

**Comment by tombruijn** [comment]
I've added the "javascript/react" app, trying to get it to work now with sourcemaps, but got a little stuck on a hanging process as detailed here: https://github.com/appsignal/appsignal-javascript/issues/469#issuecomment-764663794

Trying to now apply this PR https://github.com/appsignal/appsignal-javascript/pull/466 see that shows me any errors.

If the process continues to hang we'll probably need to test it in a not create-react-app app, because lack of the webpack config could be in the way.

**Comment by tombruijn** [comment]
I've added the `javascript/webpack` example app. I've tested the two previously linked PRs and released new versions of the JavaScript integration.
